services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uberdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator:
    build: .
    command: python -m app.run_migrations
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/uberdb"
      PYTHONPATH: "."

  user-service:
    build: .
    command: uvicorn app.user_service.main:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/uberdb"
      PYTHONPATH: "."

volumes:
  postgres_data: